# Generated by Django 3.2.8 on 2021-10-28 01:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('permanent_address', models.TextField(max_length=700)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('date_of_joining', models.DateTimeField(verbose_name='date joined')),
                ('date_of_leaving', models.DateTimeField(verbose_name='date left')),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('course', models.CharField(choices=[('IT', 'Information Technology'), ('CSE', 'Computer Science'), ('EEE', 'Electricals and Electronic Engineering')], max_length=3)),
                ('sslc_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hsc_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
