# Generated by Django 3.2.8 on 2021-11-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_joining',
            field=models.DateField(verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_leaving',
            field=models.DateField(verbose_name='date left'),
        ),
    ]
