# Generated by Django 3.2.8 on 2021-11-09 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20211109_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_joining',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_leaving',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hsc_percentage',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sslc_percentage',
        ),
    ]
