apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: python
          ports:
            containerPort: 8000
      env:
